/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './content/**/*.{md,mdx}',
    './mdx-components.tsx',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        popover: 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
        primary: 'hsl(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        destructive: 'hsl(var(--destructive))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        'content-primary': 'hsl(var(--content-primary))',
        'content-secondary': 'hsl(var(--content-secondary))',
        'content-tertiary': 'hsl(var(--content-tertiary))',
        'content-inverse': 'hsl(var(--content-inverse))',
        link: 'hsl(var(--link))',
        'link-hover': 'hsl(var(--link-hover))',
        'link-visited': 'hsl(var(--link-visited))',
        'code-bg': 'hsl(var(--code-bg))',
        'code-text': 'hsl(var(--code-text))',
        'code-border': 'hsl(var(--code-border))',
        'code-inline-bg': 'hsl(var(--code-inline-bg))',
        'code-inline-text': 'hsl(var(--code-inline-text))',
        'border-light': 'hsl(var(--border-light))',
        'border-medium': 'hsl(var(--border-medium))',
        'border-strong': 'hsl(var(--border-strong))',
        success: 'hsl(var(--success))',
        'success-foreground': 'hsl(var(--success-foreground))',
        warning: 'hsl(var(--warning))',
        'warning-foreground': 'hsl(var(--warning-foreground))',
        error: 'hsl(var(--error))',
        'error-foreground': 'hsl(var(--error-foreground))',
        'chart-1': 'hsl(var(--chart-1))',
        'chart-2': 'hsl(var(--chart-2))',
        'chart-3': 'hsl(var(--chart-3))',
        'chart-4': 'hsl(var(--chart-4))',
        'chart-5': 'hsl(var(--chart-5))',
      },
      borderRadius: {
        'radius-sm': 'calc(var(--radius) - 4px)',
        'radius-md': 'calc(var(--radius) - 2px)',
        'radius-lg': 'var(--radius)',
        'radius-xl': 'calc(var(--radius) + 4px)',
      },
    },
  },
  plugins: [],
};
